### ISSUE TITLE
dataset preparing

### ISSUE THREAD

**Issue by KylinYee** [timmh/neural-supersampling#1]
hello, timmh. may I ask for your dataset sharing?  I can't download the blender open movie assets for preparing dataset.

**Comment by timmh** [comment]
So far I have only rendered a subset of the open movies, but feel free to download what I have from [here](https://drive.google.com/drive/folders/1dQ7LyaNQtzQe7XreHWkeXAv5u4hYA80r?usp=sharing).

**Comment by wuguowuge** [comment]
> So far I have only rendered a subset of the open movies, but feel free to download what I have from [here](https://drive.google.com/drive/folders/1dQ7LyaNQtzQe7XreHWkeXAv5u4hYA80r?usp=sharing).
hello, timmh. I'm also interested in NSRR，Can I also get this dataset? This link failed before

**Comment by timmh** [comment]
My bad! I re-uploaded the dataset [here](https://f002.backblazeb2.com/file/share-twgb3cchwo4679bm/neural-supersampling-renderings.tar)
