### ISSUE TITLE
render.py

### ISSUE THREAD

**Issue by Xuex1997** [timmh/neural-supersampling#2]
Hello, timmh, a single .exr file I got after running render.py contains the color, depth, and motion vectors, but how can I store them separately, like color.png, depth.exr and vector.exr?

**Comment by timmh** [comment]
You can do so, for example, using the OpenEXR package, refer to [here](https://github.com/timmh/neural-supersampling/blob/db6403e3a84c5955cbc742facd9fc9a8569184cc/tools/reformat_depth_motion.py#L22-L36) for an example.

**Comment by Xuex1997** [comment]
Thank you very much for your reply！
