### ISSUE TITLE
about dataset preparing

### ISSUE THREAD

**Issue by wuguowuge** [timmh/neural-supersampling#3]
hi，timmh，I'm also interested in NSRR，but I can't download the blender open movie assets for preparing dataset，Can I also get this dataset?  thanks！

**Comment by timmh** [comment]
I re-uploaded the dataset [here](https://f002.backblazeb2.com/file/share-twgb3cchwo4679bm/neural-supersampling-renderings.tar)

**Comment by wuguowuge** [comment]
Sincerely thank you for your reply！

**Comment by SimonLeeGit** [comment]
> I re-uploaded the dataset [here](https://f002.backblazeb2.com/file/share-twgb3cchwo4679bm/neural-supersampling-renderings.tar)

Hi @timmh, it seems that these depth exr missing depth info. Can you re-upload it again? I'm really appreciate for your reply.
![image](https://github.com/timmh/neural-supersampling/assets/11291381/e1568147-b5e5-4d70-900b-bbc17b9a09c8)

**Comment by timmh** [comment]
It might be that the image viewer you're using just doesn't map the depth values to color correctly. Please try reading the file using OpenCV like this:
```
import os
os.environ["OPENCV_IO_ENABLE_OPENEXR"] = "1"
import cv2

cv2.imread("path_to.exr", cv2.IMREAD_UNCHANGED)
```
Please feel free to re-open this issue if that still doesn't work and let me know which file specifically you're trying to open.
