### ISSUE TITLE
run model.model with error

### ISSUE THREAD

**Issue by SimonLeeGit** [timmh/neural-supersampling#4]
root@1629d6059649:/workspace/neural-supersampling# python -m model.model
.E
======================================================================
ERROR: test_zero_upsampling (__main__.TestModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/neural-supersampling/model/model.py", line 202, in test_zero_upsampling
    zu = ZeroUpsampling(3, 2)
  File "/workspace/neural-supersampling/model/model.py", line 16, in __init__
    kernel = torch.zeros((channels, 1, upsampling_factor[1], upsampling_factor[0]), dtype=torch.float32, requires_grad=False)
TypeError: 'int' object is not subscriptable

----------------------------------------------------------------------
Ran 2 tests in 0.039s

FAILED (errors=1)

**Comment by SimonLeeGit** [comment]
I try to change the code as below, it works fine.

From:
zu = ZeroUpsampling(3, 2)

To:
zu = ZeroUpsampling(3, (2,2))

**Comment by timmh** [comment]
Good catch, should be fixed now
